<a href="https://colab.research.google.com/github/ViktorKondrashov/ITStep-AI/blob/superwised_learning/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B01_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [ ]:
import numpy as np
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [ ]:
df # таблица
df.shape # размер
df.info() # информация о таблице: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    891 non-null    int64
 1   sex       891 non-null    object
 2   age       714 non-null    float64
 3   sibsp     891 non-null    int64
 4   parch     891 non-null    int64
 5   fare      891 non-null    float64
 6   embarked  889 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

In [ ]:
mask = df["embarked"] == "Q"
mask.sum()

np.int64(77)

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

In [ ]:
mask = df['pclass'] == 1
df1 = df[mask]
df1[['sex', 'age', 'fare']]

        sex   age     fare
1    female  38.0  71.2833
3    female  35.0  53.1000
6      male  54.0  51.8625
11   female  58.0  26.5500
23     male  28.0  35.5000
..      ...   ...      ...
871  female  47.0  52.5542
872    male  33.0   5.0000
879  female  56.0  83.1583
887  female  19.0  30.0000
889    male  26.0  30.0000

[216 rows x 3 columns]

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

In [ ]:
mask = (df['sex'] == "male") & (df['age'] < 18) & (df['embarked'] == 'C')
df1 = df[mask]
df1

     pclass   sex    age  sibsp  parch      fare embarked embarked
125       3  male  12.00      1      0   11.2417        C         Q
352       3  male  15.00      1      1    7.2292        C         Q
532       3  male  17.00      1      1    7.2292        C         Q
550       1  male  17.00      0      2  110.8833        C         Q
731       3  male  11.00      0      0   18.7875        C         Q
803       3  male   0.42      0      1    8.5167        C         Q
827       2  male   1.00      0      2   37.0042        C         Q

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

In [ ]:
df.drop(columns = ['age'], inplace= True)
df
df.isnull().sum()

     pclass     sex  sibsp  parch     fare embarked embarked
0         3    male      1      0   7.2500        S         Q
1         1  female      1      0  71.2833        C         Q
2         3  female      0      0   7.9250        S         Q
3         1  female      1      0  53.1000        S         Q
4         3    male      0      0   8.0500        S         Q
..      ...     ...    ...    ...      ...      ...       ...
886       2    male      0      0  13.0000        S         Q
887       1  female      0      0  30.0000        S         Q
888       3  female      1      2  23.4500        S         Q
889       1    male      0      0  30.0000        C         Q
890       3    male      0      0   7.7500        Q         Q

[891 rows x 7 columns]

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками

In [ ]:
df.dropna(inplace=True)
df

Количество мужчин и женщин

In [ ]:
df.columns

Index(['pclass', 'sex', 'sibsp', 'parch', 'fare', 'embarked', 'embarked '], dtype='object')

In [ ]:
df.groupby(by='sex').count()

        pclass  sibsp  parch  fare  embarked  embarked
sex
female     314    314    314   314       312        314
male       577    577    577   577       577        577

Средняя цена поездки с разных портов

In [ ]:
df.groupby(by='embarked')['fare'].mean()

embarked
C    59.954144
Q    13.276030
S    27.079812
Name: fare, dtype: float64

Средняя цена от класса билета

In [ ]:
df.groupby(by='pclass')['fare'].mean()

pclass
1    84.154687
2    20.662183
3    13.675550
Name: fare, dtype: float64

In [ ]:
df.groupby(by='pclass')['fare'].min()

pclass
1    0.0
2    0.0
3    0.0
Name: fare, dtype: float64

In [ ]:
df.groupby(by='pclass')['fare'].max()

pclass
1    512.3292
2     73.5000
3     69.5500
Name: fare, dtype: float64

Средняя цена по порту и полу

In [ ]:
df.groupby(by=['sex', "embarked"])['fare'].mean()

sex     embarked
female  C           75.169805
        Q           12.634958
        S           38.740929
male    C           48.262109
        Q           13.838922
        S           21.711996
Name: fare, dtype: float64